### PR TITLE
Pull request for WAZO-2101-add-deleted-col-to-stat-tables

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/95
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/95

### CODE REVIEW

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
> Build failed.
> 
> * [wazo-tox-py37 ](https://zuul.wazo.community/logs/83/83/1ecfd723b639c1399e0f9bdba4e50b76dfb1fc9c/check/wazo-tox-py37/eeb3fb7/) : SUCCESS in 4m 26s
> * [tox-linters ](https://zuul.wazo.community/logs/83/83/1ecfd723b639c1399e0f9bdba4e50b76dfb1fc9c/check/tox-linters/d880be4/) : SUCCESS in 6m 29s
> * [debian-packaging ](https://zuul.wazo.community/logs/83/83/1ecfd723b639c1399e0f9bdba4e50b76dfb1fc9c/check/debian-packaging/0af0a51/) : SUCCESS in 8m 53s
> * [wazo-tox-integration-call-logd ](https://zuul.wazo.community/logs/83/83/1ecfd723b639c1399e0f9bdba4e50b76dfb1fc9c/check/wazo-tox-integration-call-logd/08c7da8/) : FAILURE in 19m 15s

stat_queue.deleted did not exist in that integration test run

**Pull request merged**
