### PR TITLE
purger: improve logging for retention override

### PR DESCRIPTION
**Pull request by sduthil**

### CODE REVIEW

**Comment by fblackburn1** [comment]
@bloom1 The approval is missing?

**Comment by fblackburn1** [comment]
@sduthil the mergeit tag is missing or not ready?

**Comment by bloom1** [comment]
> @bloom1 The approval is missing or not ready?

I thought I had already approved the PR, seems like I forgot. However there seems to be missing the `mergeit` tag indeed. @sduthil is it really ready to be merged?

**Review by fblackburn1 — APPROVED** [review]

**Comment by sduthil** [comment]
Yes, it's ready, sorry for the time lost

**Pull request merged**
