### PR TITLE
Pull request for WAZO-2095-cdr-destination-group-queue-answered

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/114
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/106

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Review by bloom1 — DISMISSED** [review]

**Review by bloom1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
regate

**Comment by fblackburn1** [comment]
regate

**Comment by fblackburn1** [comment]
recheck

**Pull request merged**
