### PR TITLE
WAZO-3511 Fix comparison between auth tenants and call-logd tenants

### PR DESCRIPTION
**Pull request by DrPyser**
https://wazo-dev.atlassian.net/browse/WAZO-3511

Why: data type mistmatch caused all tenants to be wiped clean

### CODE REVIEW

**Review by sduthil — CHANGES_REQUESTED** [review]
We need an automatic test to verify that data from other tenants are still present.

**Comment by DrPyser** [comment]
> We need an automatic test to verify that data from other tenants are still present.

Currently working on adding this to the integration tests.

**Comment by DrPyser** [comment]
Realized some more refactoring needed to completely replace string UUID constants with their "typed" variant (`uuid.UUID` python objects) and avoid having duplicated constants

**Review by pc-m — COMMENTED** [review]
Is it possible to add type checking to tox or pre-commit? Otherwise types are not going to catch bugs in the future.

**Review by sduthil — APPROVED** [review]

**Comment by sduthil** [comment]
+1 for adding mypy, but not in this PR:
* it is already large enough
* the automatic tests are already checking for unwanted deletions
* adding mypy means adding a lot more typing hints, AFAICT

**Pull request merged**
